def bankdb():
    data = [
        {
            "bank_code": "000014",
            "cbn_code": "044",
            "name": "Access Bank Nigeria",
            "bank_short_name": "access",
            "disabled_for_vnuban": False,
        },
        {
            "bank_code": "000014",
            "cbn_code": "063",
            "name": "Access Bank Nigeria",
            "bank_short_name": "access",
            "disabled_for_vnuban": False,
        },
        {
            "bank_code": "000010",
            "cbn_code": "050",
            "name": "Ecobank Bank",
            "bank_short_name": "ecobank",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000007",
            "cbn_code": "070",
            "name": "Fidelity Bank",
            "bank_short_name": "fidelity",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000016",
            "cbn_code": "011",
            "name": "First Bank of Nigeria",
            "bank_short_name": "firstbank",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000003",
            "cbn_code": "214",
            "name": "First City Monument Bank",
            "bank_short_name": "fcmb",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000013",
            "cbn_code": "058",
            "name": "Guaranty Trust Bank",
            "bank_short_name": "gtb",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000020",
            "cbn_code": "030",
            "name": "Heritage Bank",
            "bank_short_name": "heritage",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090121",
            "cbn_code": "50383",
            "name": "Hasal MFB",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000027",
            "cbn_code": "103",
            "name": "Globus Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "060002",
            "cbn_code": "911",
            "name": "FBNQuest Merchant Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000006",
            "cbn_code": "301",
            "name": "Jaiz Bank",
            "bank_short_name": "jaiz",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090097",
            "cbn_code": "562",
            "name": "Ekondo MFB",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000002",
            "cbn_code": "082",
            "name": "Keystone Bank",
            "bank_short_name": "keystone",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000008",
            "cbn_code": "076",
            "name": "Polaris Bank",
            "bank_short_name": "PBL",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000001",
            "cbn_code": "232",
            "name": "Sterling Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000018",
            "cbn_code": "032",
            "name": "Union Bank of Nigeria",
            "bank_short_name": "unionbank",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000004",
            "cbn_code": "033",
            "name": "United Bank for Africa",
            "bank_short_name": "uba",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000011",
            "cbn_code": "215",
            "name": "Unity Bank",
            "bank_short_name": "unity",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000017",
            "cbn_code": "035",
            "name": "Wema Bank",
            "bank_short_name": "wema",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000015",
            "cbn_code": "057",
            "name": "Zenith Bank",
            "bank_short_name": "zenith",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000015",
            "cbn_code": "057",
            "name": "Zenith Bank",
            "bank_short_name": "zenith",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090110",
            "cbn_code": "566",
            "name": "VFD MFB",
            "bank_short_name": "vfd",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000025",
            "cbn_code": "102",
            "name": "Titan Trust Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090115",
            "cbn_code": "51211",
            "name": "TCF MFB",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000026",
            "cbn_code": "302",
            "name": "Taj Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000022",
            "cbn_code": "100",
            "name": "Suntrust Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000021",
            "cbn_code": "068",
            "name": "Standard Chartered Bank",
            "bank_short_name": "standard-chartered",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000012",
            "cbn_code": "221",
            "name": "Stanbic IBTC",
            "bank_short_name": "stanbic",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090325",
            "cbn_code": "51310",
            "name": "Sparkle Bank",
            "bank_short_name": "SPKL",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090175",
            "cbn_code": "125",
            "name": "Rubies MFB",
            "bank_short_name": "RMB",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000024",
            "cbn_code": "502",
            "name": "Rand Merchant Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000023",
            "cbn_code": "101",
            "name": "Providus Bank",
            "bank_short_name": "providus",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090154",
            "cbn_code": "50823",
            "name": "CEMCS MFB",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000009",
            "cbn_code": "023",
            "name": "Citibank Nigeria",
            "bank_short_name": "citibankng",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090004",
            "cbn_code": "526",
            "name": "Parallex MFB",
            "bank_short_name": "parallex",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "060003",
            "cbn_code": "561",
            "name": "Nova Merchant Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090267",
            "cbn_code": "50211",
            "name": "Kuda MFB",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090380",
            "cbn_code": "50200",
            "name": "Kredi Bank",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "060001",
            "cbn_code": "902",
            "name": "Coronation Merchant Bank",
            "bank_short_name": "cmfb",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "090001",
            "cbn_code": "401",
            "name": "Aso Savings And Loans",
            "bank_short_name": "aso-savings",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "400001",
            "cbn_code": "501",
            "name": "FSDH Merchant Bank",
            "bank_short_name": "fsdh",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "100026",
            "cbn_code": "565",
            "name": "One Finance",
            "bank_short_name": "",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "100013",
            "cbn_code": "323",
            "name": "Accessmoney",
            "bank_short_name": "access-mobile",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "100009",
            "cbn_code": "315",
            "name": "GT Mobile Money",
            "bank_short_name": "gtb-mobile",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "100007",
            "cbn_code": "304",
            "name": "Stanbic IBTC @Ease Wal",
            "bank_short_name": "stanbic-mobile",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "100008",
            "cbn_code": "307",
            "name": "Ecobank Xpress",
            "bank_short_name": "ecobank-mobile",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "100004",
            "cbn_code": "999992",
            "name": "Paycom (Opay)",
            "bank_short_name": "paycom",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "100003",
            "cbn_code": "311",
            "name": "Parkway-Readycash",
            "bank_short_name": "parkway",
            "disabled_for_vnuban": None,
        },
        {
            "bank_code": "000012",
            "cbn_code": "039",
            "name": "Stanbic IBTC Plc",
            "bank_short_name": "Stanbic IBTC Plc",
            "disabled_for_vnuban": None,
        },
    ]

    return data
